### PR TITLE
General Layout and Routing

### PR DESCRIPTION
**Pull request by kwanstyle**
## Related Issue
https://github.com/UT-Applicataion-Development-Association/Email-Sender-Client/issues/2

## Type of Change
- [ ] Bug Fix
- [x] New Feature
- [ ] Refactoring

## Major Changes
- 引入Ant Design设计划分了Dashboard风格的框架界面
- 创建了Pages下的主要界面文件
- 定义了一级、二级和组件路由的设计

## Steps for Testing
通过webpack-dev-server在本地即可直接运行
有效路由：/, /login, /mail

## Additional Context
[还有其他注意事项吗？]

### CODE REVIEW

**Review by dinolii — APPROVED** [review]
辛苦王哥 nice work

**Comment by Falanke21** [comment]
image
I encountered this problem when doing npm install...

**Comment by Falanke21** [comment]
Is there any reason for not having a package-lock.json file? 🤔

**Comment by Falanke21** [comment]
> image
> I encountered this problem when doing npm install...

NVM, I solved this by using `npm install -g npm`, and delete node_modules then reinstall. This could happen to other people so we can put this message in the README.md ;)

**Review by Falanke21 — APPROVED** [review]
I usually commit the package-lock.json file according to https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5  
But the setup turns out fine without the lock file. @kwanstyle can decide this 👍 
Otherwise, I don't think there's anything else that I concerned about. Thx! @kwanstyle

**Comment by Falanke21** [comment]
Also, I think we can close https://github.com/UT-Applicataion-Development-Association/Email-Sender-Client/issues/2 at the same time?

**Comment by kwanstyle** [comment]
> I usually commit the package-lock.json file according to https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5
> But the setup turns out fine without the lock file. @kwanstyle can decide this 👍
> Otherwise, I don't think there's anything else that I concerned about. Thx! @kwanstyle

@Falanke21 The major reason to keep the package-lock.json file is to ensure that CI process will have the same setup as the local dev based on the given versions of dependencies. We can add it up later on

**Pull request merged**
